export { setupNaive } from '@/plugins/naive'
export { setupDirectives } from '@/plugins/directives'
export { setupCustomComponents } from '@/plugins/customComponents'
export { Icon } from '@/plugins/icon'
export { initFunction } from '@/plugins/initFunction'
export { setupComponents } from '@/plugins/components'